# =================================
# ESG Auth Service 설정 (Config Server용)
# 역할: 본사/협력사 인증, JWT 토큰 관리, 계층적 권한 시스템
# =================================

server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true

spring:
  application:
    name: auth-service

  # =================================
  # 데이터베이스 설정 - MySQL
  # =================================
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/esg_auth}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:esg_user}
    password: ${DB_PASSWORD:esg_password}
    hikari:
      # 커넥션 풀 설정
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000 # 긴 트랜잭션 감지 (성능 모니터링용)

  # =================================
  # JPA/Hibernate 설정 (N+1 문제 진단 강화)
  # =================================
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update} # create, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: true # N+1 문제 진단: Hibernate 통계 수집 활성화
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 50 # N+1 문제 진단: 50ms 이상 쿼리 로깅

# =================================
# JWT 인증 설정
# =================================
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidationPurposeOnly123456789}
  expiration: 86400000 # Access Token: 24시간 (밀리초)
  refresh-expiration: 604800000 # Refresh Token: 7일 (밀리초)
  cookie:
    name: jwt
    max-age: 86400 # 쿠키 만료시간: 24시간 (초)
    secure: ${JWT_COOKIE_SECURE:false} # HTTPS에서만 전송 (운영환경: true)
    http-only: true # XSS 방지
    same-site: strict # CSRF 방지

# =================================
# Eureka Client 설정
# =================================
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      version: ${spring.application.version:1.0.0}
      description: "ESG 인증 서비스 - 본사/협력사 로그인, JWT 관리"

# =================================
# N+1 문제 진단 강화 로깅 설정 
# =================================
logging:
  level:
    root: INFO
    com.nsmm.esg.auth_service: DEBUG
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO} # 보안 관련 로그
    org.springframework.web: ${WEB_LOG_LEVEL:INFO} # 웹 요청 로그
    # === N+1 문제 진단용 로깅 ===
    org.hibernate.SQL: DEBUG # SQL 쿼리 로깅 (N+1 진단용)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 로깅
    org.hibernate.stat: INFO # Hibernate 통계 로깅 (요약만)
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN # 세션 통계 (숨김)
    org.springframework.transaction: ${TRANSACTION_LOG_LEVEL:DEBUG} # 트랜잭션 로그 강화
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr(%-5level){highlight} %clr(%logger{36}){cyan} - %msg%n"
  file:
    name: logs/n1-performance-analysis.log # N+1 문제 분석 전용 로그 파일
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
