# =================================
# ESG Discovery Service 설정 (Eureka Server)
# 역할: 마이크로서비스 등록/발견, 로드밸런싱, 서비스 헬스체크
# 포트: 8761
# =================================

server:
  port: 8761
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  application:
    name: discovery-service

# =================================
# Eureka Server 설정
# =================================
eureka:
  # 서버 자체 설정
  server:
    # 개발환경: 자체보호모드 비활성화 (빠른 서비스 제거)
    enable-self-preservation: false
    # 제거 주기: 1초 (개발환경 전용, 운영환경: 60초)
    eviction-interval-timer-in-ms: 1000
    # 응답 캐시 갱신 주기: 30초
    response-cache-update-interval-ms: 30000
    # 응답 캐시 자동 만료 시간: 180초
    response-cache-auto-expiration-in-seconds: 180
    # 서비스 갱신 임계값: 0.85 (85% 이상 서비스가 정상일 때만 자체보호모드)
    renewal-percent-threshold: 0.85

  # 클라이언트 설정 (자기 자신은 클라이언트가 아님)
  client:
    register-with-eureka: false # 자기 자신을 등록하지 않음
    fetch-registry: false # 다른 Eureka 서버에서 레지스트리 가져오지 않음
    service-url:
      defaultZone: http://localhost:8761/eureka/

  # 인스턴스 설정
  instance:
    hostname: localhost
    prefer-ip-address: true
    # 개발환경: 빠른 하트비트 (운영환경: 30초)
    lease-renewal-interval-in-seconds: 5
    # 개발환경: 빠른 만료 (운영환경: 90초)  
    lease-expiration-duration-in-seconds: 10

# =================================
# Actuator 모니터링 설정
# =================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,eureka
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true

# =================================
# 로깅 설정
# =================================
logging:
  level:
    root: INFO
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/discovery-service.log
    max-size: 10MB
    max-history: 30
