# Eureka Server 포트
server:
  port: 8761

# 서비스 이름
spring:
  application:
    name: discovery-service

# Eureka 설정
eureka:
  client:
    register-with-eureka: false # 자기 자신을 등록하지 않음
    fetch-registry: false # 다른 Eureka에서 레지스트리 가져오지 않음
  instance:
    prefer-ip-address: true # IP 주소 우선 사용

# =================================
# 로깅 설정
# =================================
logging:
  level:
    root: INFO
    com.netflix.eureka: ${EUREKA_LOG_LEVEL:INFO}
    com.netflix.discovery: ${DISCOVERY_LOG_LEVEL:INFO}
    org.springframework.cloud.netflix: ${NETFLIX_LOG_LEVEL:INFO}
    org.springframework.web.servlet.DispatcherServlet: ${WEB_LOG_LEVEL:INFO}
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr(%-5level){highlight} %clr(%logger{36}){cyan} - %msg%n"
